### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 5 and 4

### ISSUE THREAD

**Issue by iooops** [Joshua-1995/LearnableUpsamplingLayer-Pytorch#2]
My code:
```
lu = LearnableUpsamplingLayer(100, 100)
y = torch.rand(12, 100, 275)
duration_pred = torch.rand(12, 275)
src_mask = torch.rand(12, 1, 275)
y, mel_mask = lu(y, duration_pred, src_mask)
```

Seems that the issue is from 
```
def token_boundary_grid(self, dur, src_mask):
```

S, E gives me the shape torch.Size([12, 12, 144, 275]) torch.Size([12, 12, 144, 275])

**Comment by Joshua-1995** [comment]
Apologies for the delayed reply. Thank you for informing me about the error
The issue has been resolved, and the repository has been updated

The error (line 53 at model.py)
```
src_mask = src_mask.unsqueeze(1)
```
has been fixed as
``` python
if len(src_mask.size()) == 2:
    src_mask = src_mask.unsqueeze(1)
```
